### ISSUE TITLE
Getting the error below when i run on my dataset. How can i fix it?

### ISSUE THREAD

**Issue by shankyemcee** [wenhuchen/LogicNLG#11]
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
start training 0th epoch
Traceback (most recent call last):
  File "Transformer.py", line 71, in <module>
    avg_loss += loss.item()
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=118 error=710 : device-side assert triggered
start training 0th epoch
Traceback (most recent call last):
  File "Transformer.py", line 69, in <module>
    loss = criterion(logits.view(-1, logits.shape[-1]), seqs_out.view(-1))
  File "/project/6027213/shankar5/envs/logicnlg/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/project/6027213/shankar5/envs/logicnlg/env/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/project/6027213/shankar5/envs/logicnlg/env/lib/python3.7/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/project/6027213/shankar5/envs/logicnlg/env/lib/python3.7/site-packages/torch/nn/functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:118

**Comment by wenhuchen** [comment]
It seems to me that you are optimizing some index outside of your vocabulary. Can you make sure that your target idx is always smaller than your GPT2 vocabulary -> 50K something.

**Comment by shankyemcee** [comment]
Thanks i found out what was causing the issue. When i created the full_vocab and vocab files there were some keys in the json that were duplicates because some were being counted as integers, and thus considered a different key to their string counterparts. Once i found that i just converted all tokens to string type before creating the json files and it fixed the issue.
